# Generated by Django 2.1.3 on 2018-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20181127_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('admin', models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='0', max_length=10)),
            ],
        ),
    ]
